# -*- coding: utf-8 -*-
"""Colab 시작하기

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import csv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

f = open('/content/weather.csv', encoding='CP949')
data = csv.reader(f)
header = next(data)

max_wind = 0.0

for row in data:
    if row[2] == '' :
        wind = 0
    else :
        wind = float(row[2])
    if max_wind < wind :
        max_wind = wind

print('지난 10년간 울릉도의 최대 풍속은 ', max_wind, 'm/s')
f.close()

import csv
import matplotlib.pyplot as plt

f = open('/content/weather.csv', encoding='CP949')
data = csv.reader(f)
header = next(data)

monthly_wind = [ 0 for x in range(12) ]
days_counted = [ 0 for x in range(12) ]
for row in data:
    month = int(row[0][5:7])
    if row[3] !=  '' :
        wind = float(row[3])
        monthly_wind[month-1] += wind
        days_counted[month-1] += 1

for i in range(12) :
      monthly_wind[i] /= days_counted[i]

plt.plot(monthly_wind, 'blue')
plt.show()

f.close()

import pandas as pd

weather = pd.read_csv('/content/weather.csv', index_col=0, encoding='CP949')
weather = weather.reset_index() # Convert the index '일시' into a column

print(weather.describe())
print(weather.count())
print(weather[['최대풍속','평균풍속']].mean())
weather['month'] = pd.DatetimeIndex(weather['일시']).month
weather['year'] = pd.DatetimeIndex(weather['일시']).year
means = weather.groupby('month').mean(numeric_only=True)
y_max = weather.groupby('year').max(numeric_only=True)

print(means)

import pandas as pd
df = pd.read_csv('/content/name.csv', encoding='CP949')
display(df.head())

